[project]
name = "mazegen"
version = "1.0.0"
description = "Maze generator and solver reusable module."
authors = [
    { name = "khnoman" },
    { name = "sasarbou" }
]
requires-python = ">=3.10"

[build-system]
requires = ["setuptools>=61.0", "wheel", "build"]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-dir]
"" = "mazegen"